parameters:
  jenkins:
    client:
      job:
        deploy_openstack:
          type: workflow-scm
          name: deploy-openstack
          display_name: "Deploy - OpenStack"
          discard:
            build:
              keep_num: 20
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            credentials: "gerrit"
            script: lab-pipeline.groovy
          param:
            # deployments and test settings
            STACK_TYPE:
              type: string
              default: "physical"
            INSTALL:
              type: string
              default: "core,kvm,openstack,stacklight"

            # salt master
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            SALT_MASTER_URL:
              type: string
              default: ""
            ASK_ON_ERROR:
                type: boolean
                default: 'false'
